more stuff added

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -6,10 +6,6 @@ on:
   pull_request:
     branches: [ "main" ]
 
-env:
-  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
-  BUILD_TYPE: Release
-
 jobs:
   build:
     name: ${{ matrix.os }}.${{ matrix.compiler }}.${{ matrix.build_type }}
@@ -20,26 +16,35 @@ jobs:
         os: [ ubuntu-22.04 ]
         compiler: [ 'g++-12', 'g++-11', 'clang-14', 'clang-13' ]
         build_type: [ 'Debug', 'Release' ]
-    
     steps:
     - uses: actions/checkout@v3
-
     - name: Install software
+      shell: bash
       run: |
         sudo apt install ${{ matrix.compiler }}
         sudo apt install libboost-all-dev
-        sudo apt install cmake
-        sudo apt install ninja
-
+        sudo apt install cmake ninja-build
     - name: Configure CMake
-      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
-
+      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
     - name: Build
-      # Build your program with the given configuration
-      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
+      shell: bash
+      run: |
+        if [[ ${{ matrix.compiler }} =~ clang-([0-9]+) ]]
+        then
+          export CC=clang-${BASH_REMATCH[1]}
+          export CXX=clang++-${BASH_REMATCH[1]}
+        elif [[ ${{ matrix.compiler }} =~ g++-([0-9]+) ]]
+        then
+          export CC=gcc-${BASH_REMATCH[1]}
+          export CXX=g++-${BASH_REMATCH[1]}
+        else
+          echo "error: not valid compiler parameter."
+          exit 1
+        end
+        echo "CXX=$CXX"
+        echo "CC=$CC"
+        cmake --build ${{github.workspace}}/build --config ${{ env.BUILD_TYPE }}
 
     - name: Test
       working-directory: ${{github.workspace}}/build
-      # Execute tests defined by the CMake configuration.  
-      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
       run: ctest -C ${{env.BUILD_TYPE}}
